#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocketserver"
        start-stop-daemon -S -n aesdsocketserver -d
        ;;
    stop)
        echo "Stopping aesdsocketserver"
        start-stop-daemon -K -n aesdsocketserver
        ;;
    *)
        echo "Usage $0 {start|stop}"
    exit(1)
esac